<a href="https://colab.research.google.com/github/Rose-X/NYMP/blob/main/nmpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercise 1: Creating and Manipulating NumPy Arrays**

**Create a 1D NumPy array from the list [5, 10, 15, 20, 25]. Convert the array to type float64 and print it.**



In [ ]:
import numpy as np

tb = np.array([5, 10, 15, 20, 25])

tb_float64 = tb.astype(np.float64)

print(tb_float64)


[ 5. 10. 15. 20. 25.]


**Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.**



In [ ]:
import numpy as np

tab_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Tableau 2D :")
print(tab_2d)

print("Forme TB:", tab_2d.shape)

print("Taille du tb :", tab_2d.size)


Tableau 2D :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Forme TB: (3, 3)
Taille du tb : 9


**Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.**



In [ ]:
import numpy as np
tab_3d = np.random.rand(2, 3, 4)
print(tab_3d)
print("Nombre de D:", tab_3d.ndim)
print("Forme du tb :", tab_3d.shape)


[[[0.92388347 0.79900666 0.58059833 0.32152802]
  [0.4111159  0.69211711 0.38743121 0.9218884 ]
  [0.63031576 0.58606274 0.56888434 0.98343514]]

 [[0.57638775 0.04346174 0.92552463 0.5494552 ]
  [0.91757722 0.71718873 0.94378177 0.44608884]
  [0.41446379 0.71347972 0.23659099 0.78397391]]]
Nombre de D: 3
Forme du tb : (2, 3, 4)


# Exercise 2: Advanced Array Manipulations


### **Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.**



In [ ]:
import numpy as np
tab = np.arange(10)
tab_inverse = tab[:-1] #-1 permet de faire l inverse
print("Tb inversé :", tab_inverse)


Tb inversé : [0 1 2 3 4 5 6 7 8]


### **Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.**

In [ ]:
import numpy as np
tab_2d = np.arange(12).reshape(3, 4)
sous_tab = tab_2d[:2, -2:]
print(tab_2d)
print(sous_tab)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[2 3]
 [6 7]]


### **Create a 2D NumPy array of shape (5, 5) with random integers between 0 and 10. Replace all elements greater than 5 with 0 and print the modified array.**

In [ ]:
import numpy as np
tab_2d = np.random.randint(0, 11, size=(5, 5))
tab_2d[tab_2d > 5] = 0
print(tab_2d)


[[2 0 3 0 0]
 [0 0 5 0 0]
 [1 0 4 2 0]
 [5 0 0 0 0]
 [0 4 0 0 2]]


# **Exercise 3: Array Initialization and Attributes**


## Create a 3x3 identity matrix using NumPy and print its attributes: ndim, shape, size, itemsize, and nbytes.



In [ ]:
import numpy as np

mat_identite = np.eye(3)

print("Matrice identité 3x3 :")
print(mat_identite)


print("(ndim) :", mat_identite.ndim)
print(" (shape) :", mat_identite.shape)
print(" (size) :", mat_identite.size)
print(" (itemsize) :", mat_identite.itemsize)
print(" (nbytes) :", mat_identite.nbytes)


Matrice identité 3x3 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(ndim) : 2
 (shape) : (3, 3)
 (size) : 9
 (itemsize) : 8
 (nbytes) : 72


### Create an array of 10 evenly spaced numbers between 0 and 5 using numpy.linspace(). Print the array and its datatype.



In [ ]:
import numpy as np

tab = np.linspace(0, 5, 10)

print(tab)

print("\n  INFO Données tableau :", tab.dtype)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

  INFO Données tableau : float64


### **Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution. Print the array and the sum of all elements.**



In [ ]:
import numpy as np

tab_3d = np.random.randn(2, 3, 4)


print(tab_3d)
somme_elements = np.sum(tab_3d)
print("\nSomme de tous les TBS:", somme_elements)


[[[ 1.18863843  1.52814333 -0.691359   -0.39243213]
  [ 0.50153713 -0.40071273 -0.02024321 -1.45619811]
  [ 0.25859143  0.19819638 -1.46035495  0.03459869]]

 [[ 0.15182154 -0.35198198 -0.41080258 -0.51059483]
  [ 0.6295834   0.38005311 -0.51523372  2.42659637]
  [ 0.33661799 -0.44048516 -0.01107915  0.46043469]]]

Somme de tous les TBS: 1.4333349424490964


# **Exercise 4: Fancy Indexing and Masking**


### Create a 1D NumPy array with random integers between 0 and 50 of size 20. Use fancy indexing to extract elements at indices [2, 5, 7, 10, 15] and print them.

In [ ]:
import numpy as np
tab = np.random.randint(0, 51, size=20)
indices = [2, 5, 7, 10, 15]
extrait = tab[indices]
print(tab)
print(extrait)


[48 13 50 45 47 24 28 48  5  5  2 44 35 32 28 40 31  6 33 15]
[50 24 48  2 40]


### Create a 2D NumPy array with random integers between 0 and 30 of shape (4, 5). Use a boolean mask to select all elements greater than 15 and print them.

In [ ]:
import numpy as np
tab_2d = np.random.randint(0, 31, size=(4, 5))
masque = tab_2d > 15
elements_sup_15 = tab_2d[masque]
print(tab_2d)
print(elements_sup_15)


[[ 5 17 13 21 13]
 [30 24 20  7  5]
 [24 26 17 29 25]
 [25 30 21 25 17]]
[17 21 30 24 20 24 26 17 29 25 25 30 21 25 17]


### Create a 1D NumPy array of 10 random integers between -10 and 10. Use a boolean mask to set all negative values to zero and print the modified array.

In [ ]:
import numpy as np
tab = np.random.randint(-10, 11, size=10)
masque_negatif = tab < 0
tab[masque_negatif] = 0
print(tab)


[ 0  1 10  6  0  0  0  0  0  0]


# Exercise 5: Combining and Splitting Arrays


### **Create two 1D NumPy arrays of length 5 with random integers between 0 and 10. Concatenate the two arrays and print the result.**



In [ ]:
import numpy as np
tab = np.random.randint(-10, 11, size=10)
masque_n = tab < 0
tab[masque_n] = 0
print(tab)


[ 0  3  0  6 10  0  0  1  5  4]


### **Create a 2D NumPy array of shape (6, 4) with random integers between 0 and 10. Split the array into two equal parts along the row axis and print them.**

In [ ]:
import numpy as np

tab_2d = np.random.randint(0, 11, size=(6, 4))

partie1, partie2 = np.split(tab_2d, 2, axis=0)
print(tab_2d)
print(partie1)
print(partie2)


[[ 5  1  8  5]
 [ 1  7  1  9]
 [ 4  9  1  1]
 [ 9  4  0  6]
 [ 5  8  0 10]
 [ 0  6  1  5]]
[[5 1 8 5]
 [1 7 1 9]
 [4 9 1 1]]
[[ 9  4  0  6]
 [ 5  8  0 10]
 [ 0  6  1  5]]


### **Create a 2D NumPy array of shape (3, 6) with random integers between 0 and 10. Split the array into three equal parts along the column axis and print them**

In [ ]:
import numpy as np
tab_2d = np.random.randint(0, 11, size=(3, 6))
partie1, partie2, partie3 = np.split(tab_2d, 3, axis=1)
print(tab_2d)
print(partie1)
print(partie2)
print(partie3)


[[ 4  1  8  3  2  8]
 [10  2  3  8  1  5]
 [ 4  6  3  2  4  1]]
[[ 4  1]
 [10  2]
 [ 4  6]]
[[8 3]
 [3 8]
 [3 2]]
[[2 8]
 [1 5]
 [4 1]]


# Exercise 6: Mathematical Functions and Aggregations



### Create a 1D NumPy array with random integers between 1 and 100 of size 15. Compute and print the mean, median, standard deviation, and variance of the array.

In [ ]:
import numpy as np

tab = np.random.randint(1, 101, size=15)

moyenne = np.mean(tab)
mediane = np.median(tab)
ecart_type = np.std(tab)
variance = np.var(tab)

print(tab)

print("\nStatistiques :")
print("Moyenne :", moyenne)
print("Médiane :", mediane)
print("Écart-type :", ecart_type)
print("Variance :", variance)


[26 34 15 21 44 85 99 97 41 74 77 53 71 14 28]

Statistiques :
Moyenne : 51.93333333333333
Médiane : 44.0
Écart-type : 28.669302204429197
Variance : 821.9288888888889


### Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 50. Compute and print the sum of each row and each column.

In [ ]:
import numpy as np

tab_2d = np.random.randint(1, 51, size=(4, 4))
somme_lignes = np.sum(tab_2d, axis=1)
somme_colonnes = np.sum(tab_2d, axis=0)
print(tab_2d)
print(somme_lignes)
print('//')
print(somme_colonnes)


[[ 6 34 20 28]
 [35 36 39  5]
 [23 45 12 25]
 [24  7 46 33]]
[ 88 115 105 110]
//
[ 88 122 117  91]


### Create a 3D NumPy array of shape (2, 3, 4) with random integers between 1 and 20. Find the maximum and minimum values along each axis and print them.

In [ ]:
import numpy as np

tab_3d = np.random.randint(1, 21, size=(2, 3, 4))

max_axis0 = np.max(tab_3d, axis=0)
max_axis1 = np.max(tab_3d, axis=1)
max_axis2 = np.max(tab_3d, axis=2)

min_axis0 = np.min(tab_3d, axis=0)
min_axis1 = np.min(tab_3d, axis=1)
min_axis2 = np.min(tab_3d, axis=2)

print("Tableau 3D (2x3x4) :")
print(tab_3d)

print("\nValeurs maximales :")
print("Max sur l'axe 0 (entre les blocs) :\n", max_axis0)
print("Max sur l'axe 1 (entre les lignes) :\n", max_axis1)
print("Max sur l'axe 2 (entre les colonnes) :\n", max_axis2)

print("\nValeurs mini :")
print("Min sur l'axe 0 (entre les blocs) :\n", min_axis0)
print("Min sur l'axe 1 (entre les lignes) :\n", min_axis1)
print("Min sur l'axe 2 (entre les colonnes) :\n", min_axis2)



Tableau 3D (2x3x4) :
[[[ 4 16 19  3]
  [12  7 19 19]
  [15 19 19  3]]

 [[19 12 12  4]
  [20 19  2 19]
  [16 15 14  5]]]

Valeurs maximales :
Max sur l'axe 0 (entre les blocs) :
 [[19 16 19  4]
 [20 19 19 19]
 [16 19 19  5]]
Max sur l'axe 1 (entre les lignes) :
 [[15 19 19 19]
 [20 19 14 19]]
Max sur l'axe 2 (entre les colonnes) :
 [[19 19 19]
 [19 20 16]]

Valeurs mini :
Min sur l'axe 0 (entre les blocs) :
 [[ 4 12 12  3]
 [12  7  2 19]
 [15 15 14  3]]
Min sur l'axe 1 (entre les lignes) :
 [[ 4  7 19  3]
 [16 12  2  4]]
Min sur l'axe 2 (entre les colonnes) :
 [[3 7 3]
 [4 2 5]]


# Exercise 7: Reshaping and Transposing Arrays


### Create a 1D NumPy array with the numbers from 1 to 12. Reshape the array to a 2D array of shape (3, 4) and print it.



In [ ]:
import numpy as np
tab_1d = np.arange(1, 13)
tab_2d = tab_1d.reshape(3, 4)
print(tab_2d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Transpose the array and print the transposed array.

In [ ]:
import numpy as np

tab_2d = np.random.randint(1, 11, size=(3, 4)) ## Création d'un tb 2D (3x4)  nb aléatoires entre 1 et 10


tab_transpose = tab_2d.T

print("Tableau original (3x4) :")
print(tab_2d)

print("\nTableau transposé (4x3) :")
print(tab_transpose)


Tableau original (3x4) :
[[ 1  9  5  7]
 [ 8  6 10  5]
 [ 8  5 10  9]]

Tableau transposé (4x3) :
[[ 1  8  8]
 [ 9  6  5]
 [ 5 10 10]
 [ 7  5  9]]


### Create a 2D NumPy array of shape (2, 3) with random integers between 1 and 10. Flatten the array to 1D and print the result.

In [ ]:
import numpy as np
tab_2d = np.random.randint(1, 11, size=(2, 3))
tab_1d = tab_2d.flatten()
print(tab_2d)
print(tab_1d)


[[4 3 8]
 [6 7 9]]
[4 3 8 6 7 9]


# Exercise 8: Broadcasting and Vectorized Operations




### Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Subtract the mean of each column from the respective column elements and print the result.

In [ ]:
import numpy as np
tab_2d = np.random.randint(1, 11, size=(3, 4))
moyenne_colonnes = np.mean(tab_2d, axis=0)
tab_centre = tab_2d - moyenne_colonnes
print(tab_2d)
print(moyenne_colonnes)
print(tab_centre)


[[ 8 10  9  4]
 [ 1  1  6  6]
 [ 1  3  7 10]]
[3.33333333 4.66666667 7.33333333 6.66666667]
[[ 4.66666667  5.33333333  1.66666667 -2.66666667]
 [-2.33333333 -3.66666667 -1.33333333 -0.66666667]
 [-2.33333333 -1.66666667 -0.33333333  3.33333333]]


### Create two 1D NumPy arrays of length 4 with random integers between 1 and 5. Use broadcasting to compute and print the outer product of the two arrays.

In [ ]:
import numpy as np

tab1 = np.random.randint(1, 6, size=4)
tab2 = np.random.randint(1, 6, size=4)
produit_exterieur = tab1[:, np.newaxis] * tab2
print(tab1)
print(tab2)
print(produit_exterieur)


[1 1 5 1]
[3 3 3 2]
[[ 3  3  3  2]
 [ 3  3  3  2]
 [15 15 15 10]
 [ 3  3  3  2]]


### Create a 2D NumPy array of shape (4, 5) with random integers between 1 and 10. Add 10 to all elements of the array that are greater than 5 and print the modified array.

In [ ]:
import numpy as np
tab_2d = np.random.randint(1, 11, size=(4, 5))
tab_2d[tab_2d > 5] += 10
print(tab_2d)


[[19  5  5 18 19]
 [16 19 17  4  3]
 [19  4 20 16  2]
 [20  4  1  5  4]]


#Exercise 9: Sorting and Searching Arrays


### Create a 1D NumPy array with random integers between 1 and 20 of size 10. Sort the array in ascending order and print the sorted array.

In [ ]:
import numpy as np

tab = np.random.randint(1, 21, size=10)

tab_tri = np.sort(tab)

print("Tab OG :")
print(tab)

print("Tab trié:")
print(tab_tri)


Tab OG :
[12 15 17 18 13 14  2  5 17 12]
Tab trié:
[ 2  5 12 12 13 14 15 17 17 18]


###Create a 2D NumPy array of shape (3, 5) with random integers between 1 and 50. Sort the array by the second column and print the result
> Ajouter une citation



In [ ]:
import numpy as np

tab = np.random.randint(1, 51, size=(3, 5))

tab_tri = tab[tab[:, 1].argsort()]

print("Tab OG non change  :")
print(tab)

print("\Tab trié par 2 eme colonne :")
print(tab_tri)

Tab original :
[[ 5 10 48 12 46]
 [33 47 10 47 15]
 [29 43 49 47 46]]

Tab trié par la deuxième colonne :
[[ 5 10 48 12 46]
 [29 43 49 47 46]
 [33 47 10 47 15]]


### Create a 1D NumPy array with random integers between 1 and 100 of size 15. Find and print the indices of all elements greater than 50.

In [ ]:
import numpy as np
tab = np.random.randint(1, 101, size=15)
indices_sup_50 = np.argwhere(tab > 50).flatten()
print(tab)
print(indices_sup_50)
print(tab[indices_sup_50])



[13 27 77 91 47 96 60 57 13 25 69 87 95 73 45]
[ 2  3  5  6  7 10 11 12 13]
[77 91 96 60 57 69 87 95 73]


# Exercise 10: Linear Algebra with NumPy

Create a 2D NumPy array of shape (2, 2) with random integers between 1 and 10. Compute and print the determinant of the array

In [ ]:
import numpy as np

mat = np.random.randint(1, 11, size=(2, 2)) # création d un tb aléatoire (mat)
#11 car 11-1= 10

cal = np.linalg.det(mat) #cal du tb


print(mat)

print(cal)


Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 5. Compute and print the eigenvalues and eigenvectors of the array.

In [ ]:
#On doit juste changer la valeur de matrice
import numpy as np

mat = np.random.randint(1, 6, size=(3, 3))


cal = np.linalg.det(mat) #cal du tb


print(mat)

print(cal)


Create two 2D NumPy arrays of shape (2, 3) and (3, 2) with random integers between 1 and 10. Compute and print the matrix product of the two arrays.

In [ ]:
import numpy as np

mat_a = np.random.randint(1, 11, size=(2, 3))
mat_b = np.random.randint(1, 11, size=(3, 2))

prod_mat = np.matmul(mat_a, mat_b)  # Ou mat_a  mat_b

print('\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\')
print(mat_a)

print('\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\')

print(mat_b)
print('\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\')

print(prod_mat)



\\\\\\\\\\\\\\
[[ 1 10  8]
 [ 4  7  9]]

\\\\\\\\\\\\\\
[[ 8 10]
 [ 9  2]
 [ 7  9]]

\\\\\\\\\\\\\\
[[154 102]
 [158 135]]


# Exercise 11: Random Sampling and Distributions

Create a 1D NumPy array of 10 random samples from a uniform distribution over [0, 1) and print the array.



In [ ]:
import numpy as np

tb1 = np.random.rand(10) #génère 10  nb alt

print(tb1)


[0.64098095 0.11321146 0.99333754 0.68408837 0.14081056 0.25636555
 0.50377583 0.02061602 0.68281721 0.47245892]


Create a 2D NumPy array of shape (3, 3) with random samples from a normal distribution with mean 0 and standard deviation 1. Print the array.

In [ ]:
import numpy as np

mat_normale = np.random.randn(3, 3) #Génère une matrice 3x3 avec des valeurs issues d'une distribution normale standard (μ=0, σ=1).

print(mat_normale)


Create a 1D NumPy array of 20 random integers between 1 and 100. Compute and print the histogram of the array with 5 bins.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

tab = np.random.randint(1, 101, size=20)

hist, bins = np.histogram(tab, bins=5)

print("Tableau de 20  :", tab)

print("\nHistogramme  :", hist)

# Affiche les bornes des bins
print("\nBornes des bins :", bins)

plt.hist(tab, bins=5, edgecolor='black', alpha=0.7)  # Dessine l'histogramme
plt.title("Histogramme des nombres générés")  # Titre du graphique
plt.xlabel("Valeur")  # Axe X
plt.ylabel("Fréquence")  # Axe Y

plt.show()


#Exercise 12: Advanced Indexing and Selection

Create a 2D NumPy array of shape (5, 5) with random integers between 1 and 20. Select and print the diagonal elements of the array.



In [ ]:
import numpy as np  # Importation de NumPy

mat = np.random.randint(1, 21, size=(5, 5))  #tb 2D 5 sur 5 NB

diag_elements = np.diag(mat)

print(mat)


print(diag_elements)


Create a 1D NumPy array of 10 random integers between 1 and 50. Use advanced indexing to select and print all elements that are prime numbers.

In [ ]:
import numpy as np

def nbp(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):  # Vérifie la divisibilité
        if n % i == 0:
            return False
    return True

tab = np.random.randint(1, 51, size=10) #gén le tb

pc = np.array([nbp(num) for num in tab])

primes = tab[pc]

print(tab)

print(primes)


Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 10. Select and print all elements that are even numbers.

In [ ]:
import numpy as np

mat = np.random.randint(1, 11, size=(4, 4)) # Génère un tableau 2D (4x4) avec des entiers entre 1 et 10


mask_pairs = (mat % 2 == 0) # permet de faire le booléen pour trouver les nb p

pairs = mat[mask_pairs]

print(mat)

print(pairs)


# Exercise 13: Handling Missing Data

Create a 1D NumPy array of length 10 with random integers between 1 and 10. Introduce np.nan at random positions and print the array.



In [ ]:
import numpy as np

tab = np.array(np.random.randint(1, 11, size=10), dtype=float) ## Génère un tableau 1D de 10 entiers entre 1 et 10, puis convertit en float


nb_nan = np.random.randint(1, 4)  # Entre 1 et 3 NaNs
indices_nan = np.random.choice(len(tab), nb_nan, replace=False)  # Indices uniques

tab[indices_nan] = np.nan


print(tab)


Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Replace all elements that are less than 5 with np.nan and print the array.

In [ ]:
import numpy as np

mat = np.array(np.random.randint(1, 11, size=(3, 4)), dtype=float)

mask = mat < 5

mat[mask] = np.nan

print(mat)


# Exercise 14: Performance Optimization with NumPy

Create a large 1D NumPy array with 1 million random integers between 1 and 100. Compute the mean and standard deviation using NumPy functions and measure the time taken.

In [ ]:
import numpy as np
import time

tab = np.random.randint(1, 101, size=1_000_000)

start_time = time.time()
mean_value = np.mean(tab)
std_dev = np.std(tab)
elapsed_time = time.time() - start_time

print(mean_value, std_dev, elapsed_time)


Create two large 2D NumPy arrays of shape (1000, 1000) with random integers between 1 and 10. Perform element-wise addition and measure the time taken.

In [ ]:
import numpy as np
import time

mat1 = np.random.randint(1, 11, size=(1000, 1000))
mat2 = np.random.randint(1, 11, size=(1000, 1000))

start_time = time.time()
result = mat1 + mat2  # Addition élément par élément
elapsed_time = time.time() - start_time


print(elapsed_time)


Create a 3D NumPy array of shape (100, 100, 100) with random integers between 1 and 10. Compute the sum along each axis and measure the time taken

In [ ]:
import numpy as np
import time

tab_3d = np.random.randint(1, 11, size=(100, 100, 100))

# Mesure du temps
debut_tps = time.time()
somme_ax0 = np.sum(tab_3d, axis=0)
somme_ax1 = np.sum(tab_3d, axis=1)
somme_ax2 = np.sum(tab_3d, axis=2)
tps_ecoule = time.time() - debut_tps

print(tps_ecoule)


# Exercise 15: Cumulative and Aggregate Functions

Create a 1D NumPy array with the numbers from 1 to 10. Compute and print the cumulative sum and cumulative product of the array.

In [ ]:
import numpy as np

tab = np.arange(1, 11)

somme_cumul = np.cumsum(tab)
produit_cumul = np.cumprod(tab)

print("Sm :", somme_cumul)
print("Pd com :", produit_cumul)


Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 20. Compute and print the cumulative sum along the rows and the columns

In [ ]:
import numpy as np

mat = np.random.randint(1, 21, size=(4, 4)) #tb 4FOIS4

somme_cumul_lignes = np.cumsum(mat, axis=1) #cal la som
somme_cumul_colonnes = np.cumsum(mat, axis=0)

# Affichage des résultats
print( mat)
print( somme_cumul_lignes)
print( somme_cumul_colonnes)


Create a 1D NumPy array with 10 random integers between 1 and 50. Compute and print the minimum, maximum, and sum of the array.

In [ ]:
import numpy as np

tab = np.random.randint(1, 51, size=10) # Création d'un tableau 1D avec 10 entiers aléatoires entre 1 et 50


val_min = np.min(tab)
val_max = np.max(tab)
somme_totale = np.sum(tab)

print("Tableau :", tab)
print("Minimum :", val_min)
print("Maximum :", val_max)
print("Somme totale :", somme_totale)


# Exercise 16: Working with Dates and Times

Create an array of 10 dates starting from today with a daily frequency and print the array.

In [ ]:
import numpy as np

dates = np.arange(np.datetime64('today'), np.datetime64('today') + 10, dtype='datetime64[D]') #Ajoute 10 jours à la date d’aujourd’hui.


print(dates)


Create an array of 5 dates starting from January 1, 2022 with a monthly frequency and print the array.



In [ ]:
import numpy as np

dates = np.arange(np.datetime64('2022-01'), np.datetime64('2022-06'), dtype='datetime64[M]') #on change juste la date

print(dates)


['2022-01' '2022-02' '2022-03' '2022-04' '2022-05']


Create a 1D array with 10 random timestamps in the year 2023. Convert the timestamps to NumPy datetime64 objects and print the result.

In [ ]:
import numpy as np

# Génération de 10 timestamps aléatoires dans l'année 2023
timestamps = np.random.randint(
    np.datetime64('2023-01-01T00:00:00').astype('int'),
    np.datetime64('2023-12-31T23:59:59').astype('int'),
    size=10
)

dates = timestamps.astype('datetime64[s]')

print(dates)


# Exercise 17: Creating Arrays with Custom Data Types

Create a 1D NumPy array of length 5 with custom data type to store integers and their corresponding binary representation as strings. Print the array.

In [ ]:
import numpy as np

dt = np.dtype([('entier', np.int32), ('binaire', 'U10')]) # peremt  stocker un entier 32 bits.

tab = np.array([(5, bin(5)[2:]), (10, bin(10)[2:]), (15, bin(15)[2:]), #creation du tb en binaire
                (20, bin(20)[2:]), (25, bin(25)[2:])], dtype=dt)

print(tab)


Create a 2D NumPy array of shape (3, 3) with a custom data type to store complex numbers. Initialize the array with some complex numbers and print the array.

In [ ]:
import numpy as np

tab_complexe = np.array([ # Création tb 2D (3x3) avec des nombres complexes avec option avec

    [1+2j, 3+4j, 5+6j],
    [7+8j, 9+10j, 11+12j],
    [13+14j, 15+16j, 17+18j]
], dtype=np.complex128)

print(tab_complexe)


Create a structured array to store information about books with fields: title (string), author (string), and pages (integer). Add information for three books and print the structured array.

In [ ]:
import numpy as np

dt = np.dtype([('titre', 'U50'), ('auteur', 'U50'), ('pages', np.int32)]) #le dt pour mettre les infos legendes

livres = np.array([ #le tb
    ('Naruto Vol. 1', 'Masashi Kishimoto', 192),
    ('Naruto Vol. 27', 'Masashi Kishimoto', 216),
    ('Naruto Vol. 72', 'Masashi Kishimoto', 220)
], dtype=dt) # cette options permet de mettre les 3 infos sur la meme legende j'ai trouver ca sur le web ! car j v un pb !

print(livres)



[('Naruto Vol. 1', 'Masashi Kishimoto', 192)
 ('Naruto Vol. 27', 'Masashi Kishimoto', 216)
 ('Naruto Vol. 72', 'Masashi Kishimoto', 220)]
